apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    zalando.org/schedule-actions: |
      [
        {"schedule": "45 22 * * *", "replicas": "1"},
        {"schedule": "45 1 * * *", "replicas": "0"}
      ]
  labels:
    app.kubernetes.io/instance: example
    app.kubernetes.io/name: example
  name: example-deployment
  namespace: default
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app.kubernetes.io/instance: example
      app.kubernetes.io/name: example
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app.kubernetes.io/instance: example
        app.kubernetes.io/name: example
    spec:
      containers:
      - image: k8s.gcr.io/pause:latest
        imagePullPolicy: IfNotPresent
        name: example-pause
        resources:
          limits:
            cpu: 100
            memory: 128Mi
          requests:
            cpu: 100
            memory: 128Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      priorityClassName: low
      restartPolicy: Always
      schedulerName: default-scheduler
      serviceAccount: default
      serviceAccountName: default
      terminationGracePeriodSeconds: 30
